<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Territories.aspx.cs" Inherits="Northwind_Territories" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Territories</title>
	<style type="text/css">
		.max_width
		{
			width: 100%;
		}
		td.field_caption
		{
			font-weight: bold;
			text-align: right;
			margin-right: 2px;
		}
	</style>
</head>
<body>
	<h1>Territories</h1>
	<p>This page demonstrates usage of GridView, FormView and DropDownList with the SqlDataSource. DropDownList is
used to implement master-details view. FormView is used for new record insertion.</p>
    <form id="frm" runat="server">
    <div>
		<asp:Panel ID="pnlData" runat="server">
    		<asp:SqlDataSource ID="srcTerritories" runat="server" 
				ConnectionString="<%$ ConnectionStrings:Northwind %>" 
				ProviderName="System.Data.SqlClient" EnableCaching="true" CacheExpirationPolicy="Sliding"
				SelectCommand="SP_TERRITORIES_BY_REGION_GET" SelectCommandType="StoredProcedure" 
				OnDeleted="dataSource_SqlCommandDone"
				OnInserted="dataSource_SqlCommandDone" 
				OnSelected="dataSource_SqlCommandDone"
				OnUpdated="dataSource_SqlCommandDone" 
				InsertCommand="SP_TERRITORY_UPD" InsertCommandType="StoredProcedure" 
				UpdateCommand="SP_TERRITORY_UPD" UpdateCommandType="StoredProcedure" 
				OnUpdating="srcTerritories_InsertingUpdating"
				OnSelecting="srcTerritories_Selecting"
				OnInserting="srcTerritories_InsertingUpdating" 
				DeleteCommand="DELETE FROM TERRITORIES WHERE TERRITORYID = @TERRITORYID">
				<SelectParameters>
					<asp:ControlParameter ControlID="cmbRegions" Name="PNI_REGION_ID" 
						PropertyName="SelectedValue" />
				</SelectParameters>
				<InsertParameters>
					<asp:Parameter Name="PVI_TERRITORY_ID" />
					<asp:Parameter Name="PVI_TERRITORY_DESC" />
					<asp:ControlParameter ControlID="cmbRegions" Name="PNI_REGION_ID" 
						PropertyName="SelectedValue" />
				</InsertParameters>
				<UpdateParameters>
					<asp:Parameter Name="PVI_TERRITORY_ID" />
					<asp:Parameter Name="PVI_TERRITORY_DESC" />
					<asp:ControlParameter ControlID="cmbRegions" Name="PNI_REGION_ID" 
						PropertyName="SelectedValue" />
				</UpdateParameters>		
			</asp:SqlDataSource>
	    
    		<asp:SqlDataSource ID="srcRegions" runat="server" 
				ConnectionString="<%$ ConnectionStrings:Northwind %>" 
				DataSourceMode="DataReader" ProviderName="System.Data.SqlClient" 
				SelectCommand="
SELECT REGIONID,
       REGIONDESCRIPTION
  FROM DBO.REGION
 WHERE REGIONID <> @INVALID_REGION_ID" 
				OnSelecting="srcRegions_Selecting" 
				OnDeleted="dataSource_SqlCommandDone" 
				OnInserted="dataSource_SqlCommandDone"
				OnSelected="dataSource_SqlCommandDone" 
				OnUpdated="dataSource_SqlCommandDone">
				<SelectParameters>
					<asp:Parameter Name="INVALID_REGION_ID" />
				</SelectParameters>
			</asp:SqlDataSource>
				
			Select a region: 
			<asp:DropDownList ID="cmbRegions" runat="server" 
				DataTextField="RegionDescription" DataValueField="RegionID" AutoPostBack="True"
				OnSelectedIndexChanged="cmbRegions_SelectedIndexChanged">
			</asp:DropDownList>
			
			<asp:Panel runat="server" ID="pnlTerritories" Visible="false">
				<div>Region's territories:</div>
				
				<asp:GridView ID="grdTerritories" runat="server" AutoGenerateColumns="False" 
					DataKeyNames="TerritoryID" DataSourceID="srcTerritories" 
					AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateDeleteButton="True">
					<Columns>
						<asp:BoundField DataField="TerritoryID" HeaderText="ID" 
							ReadOnly="True" SortExpression="TerritoryID" />
						<asp:BoundField DataField="TerritoryDescription" 
							HeaderText="Description" SortExpression="TerritoryDescription" />
					</Columns>
				</asp:GridView>
				<br />
				Define a new territory:
				<asp:FormView ID="frmTerritory" runat="server" 
					DataSourceID="srcTerritories" DefaultMode="Insert" Width="400px">
					<InsertItemTemplate>
						<table class="max_width">
							<tr>
								<td align="right" class="field_caption" width="25%">Description:</td>
								<td>
									<asp:TextBox ID="txtDescription" runat="server" MaxLength="50" 
										Text='<%# Bind("TerritoryDescription") %>' Width="100%"></asp:TextBox>
								</td>
							</tr>
							<tr>
								<td align="right" class="field_caption">ID:</td>
								<td>
									<asp:TextBox ID="txtID" runat="server" MaxLength="20" 
										Text='<%# Bind("TerritoryID") %>' Width="100%"></asp:TextBox>
								</td>
							</tr>
							<tr bgcolor="#CCCCFF">
								<td>
									<asp:Button ID="btnInsertTerritory" runat="server" CommandName="Insert" 
										Text="OK" Width="80px" />
								</td>
								<td align="right">
									<asp:Button ID="btnCancelTerritory" runat="server" CommandArgument="Cancel" 
										Text="Cancel" Width="80px" />
								</td>
							</tr>
						</table>
					</InsertItemTemplate>
				</asp:FormView>
			</asp:Panel>
		</asp:Panel>
		
		<asp:Label runat="server" ID="lblError" 
			Text="An error ocurred during accessing the database. Please try again later." 
			ForeColor="Red"
			Visible="false" />    
    </div>
    </form>
</body>
</html>
