//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskClient.TaskWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TaskClient.TaskWcfService.TaskStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedTo {
            get {
                return this.AssignedToField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedToField, value) != true)) {
                    this.AssignedToField = value;
                    this.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TaskClient.TaskWcfService.TaskStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskNumber {
            get {
                return this.TaskNumberField;
            }
            set {
                if ((this.TaskNumberField.Equals(value) != true)) {
                    this.TaskNumberField = value;
                    this.RaisePropertyChanged("TaskNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskStatus", Namespace="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")]
    public enum TaskStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Assigned = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Overdue = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedOnTime = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompletedLate = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")]
    [System.SerializableAttribute()]
    public partial class FaultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskWcfService.ITaskService")]
    public interface ITaskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/AddTask", ReplyAction="http://tempuri.org/ITaskService/AddTaskResponse")]
        int AddTask(TaskClient.TaskWcfService.Task t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/GetTask", ReplyAction="http://tempuri.org/ITaskService/GetTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaskClient.TaskWcfService.FaultInfo), Action="http://tempuri.org/ITaskService/GetTaskFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")]
        TaskClient.TaskWcfService.Task GetTask(int taskNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/AssignTask", ReplyAction="http://tempuri.org/ITaskService/AssignTaskResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaskClient.TaskWcfService.FaultInfo), Action="http://tempuri.org/ITaskService/AssignTaskFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")]
        void AssignTask(int taskNumber, string owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/GetTasksByOwner", ReplyAction="http://tempuri.org/ITaskService/GetTasksByOwnerResponse")]
        TaskClient.TaskWcfService.Task[] GetTasksByOwner(string owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/IsTaskCompleted", ReplyAction="http://tempuri.org/ITaskService/IsTaskCompletedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TaskClient.TaskWcfService.FaultInfo), Action="http://tempuri.org/ITaskService/IsTaskCompletedFaultInfoFault", Name="FaultInfo", Namespace="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")]
        bool IsTaskCompleted(int taskNumber);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITaskService/MarkTaskCompleted")]
        void MarkTaskCompleted(int taskNumber);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITaskService/DeleteTask")]
        void DeleteTask(int taskNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskServiceChannel : TaskClient.TaskWcfService.ITaskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskServiceClient : System.ServiceModel.ClientBase<TaskClient.TaskWcfService.ITaskService>, TaskClient.TaskWcfService.ITaskService {
        
        public TaskServiceClient() {
        }
        
        public TaskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddTask(TaskClient.TaskWcfService.Task t) {
            return base.Channel.AddTask(t);
        }
        
        public TaskClient.TaskWcfService.Task GetTask(int taskNumber) {
            return base.Channel.GetTask(taskNumber);
        }
        
        public void AssignTask(int taskNumber, string owner) {
            base.Channel.AssignTask(taskNumber, owner);
        }
        
        public TaskClient.TaskWcfService.Task[] GetTasksByOwner(string owner) {
            return base.Channel.GetTasksByOwner(owner);
        }
        
        public bool IsTaskCompleted(int taskNumber) {
            return base.Channel.IsTaskCompleted(taskNumber);
        }
        
        public void MarkTaskCompleted(int taskNumber) {
            base.Channel.MarkTaskCompleted(taskNumber);
        }
        
        public void DeleteTask(int taskNumber) {
            base.Channel.DeleteTask(taskNumber);
        }
    }
}
