<%@ Page Language="C#" Title="XPath Binding" MasterPageFile="~/Northwind/Master/Northwind.master"
	AutoEventWireup="true" CodeFile="DvdList.aspx.cs" Inherits="Northwind.UI.Ado.DvdListPage" culture="auto" meta:resourcekey="PageResource1" uiculture="auto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="NorthwindContentPlaceHolder" runat="Server">
	<h2>
		XPath Binding</h2>
	<p>
		This page demonstrates usage of <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.xmldatasource.aspx" target="_blank">XmlDataSource</a> with XPath binding expressions
		and with <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.treeview.aspx" target="_blank">TreeView</a>
		<asp:XmlDataSource ID="srcDvds" runat="server" DataFile="~/App_Data/DVDList.xml"
			XPath="/DvdList/DVD[@ID!=&quot;0&quot;]" CacheDuration="600" 
			CacheExpirationPolicy="Sliding"></asp:XmlDataSource>
		<asp:XmlDataSource ID="srcMovies" runat="server" CacheDuration="600" 
			CacheExpirationPolicy="Sliding" DataFile="~/App_Data/DVDList.xml" 
			TransformFile="~/Transforms/Dvds2Movies.xslt"></asp:XmlDataSource>
		<table width="100%">
			<tr>
				<td>
					<asp:GridView ID="grdDvds" runat="server" AutoGenerateColumns="False" 
						DataSourceID="srcDvds" meta:resourcekey="grdDvdsResource1">
						<Columns>
							<asp:TemplateField HeaderText="DVDs" meta:resourcekey="TemplateFieldResource2">
								<ItemTemplate>
									<b>
										<%# XPath("Title") %></b>
									<br />
									<%# XPath("Director") %>
									<br />
									<br />
									<asp:GridView ID="grdStarring" AutoGenerateColumns="False" DataSource='<%# XPathSelect("./Starring/Star") %>'
										runat="server" meta:resourcekey="grdStarringResource1">
										<Columns>
											<asp:TemplateField meta:resourcekey="TemplateFieldResource1">
												<HeaderTemplate>
													<i>Starring...</i>
												</HeaderTemplate>
												<ItemTemplate>
													<%# XPath(".") %>
													<br />
												</ItemTemplate>
												<ItemStyle HorizontalAlign="Center" />
											</asp:TemplateField>
										</Columns>
									</asp:GridView>
								</ItemTemplate>
							</asp:TemplateField>
						</Columns>
					</asp:GridView>
				</td>
				<td>
					<asp:TreeView ID="tvwDvds" runat="server" DataSourceID="srcMovies" 
						ImageSet="Arrows" AutoGenerateDataBindings="False" ShowCheckBoxes="Leaf" 
						meta:resourcekey="tvwDvdsResource1">
						<DataBindings>
							<asp:TreeNodeBinding DataMember="Movies" Text="Movies" Value="Movies" 
								meta:resourcekey="TreeNodeBindingResource1" />
							<asp:TreeNodeBinding DataMember="DVD" TextField="Title" ValueField="ID" 
								meta:resourcekey="TreeNodeBindingResource2" />
							<asp:TreeNodeBinding DataMember="Star" TextField="Name" 
								meta:resourcekey="TreeNodeBindingResource3" />
						</DataBindings>
						<HoverNodeStyle Font-Underline="True" ForeColor="#5555DD" />
						<NodeStyle Font-Names="Tahoma" Font-Size="10pt" ForeColor="Black" 
							HorizontalPadding="5px" NodeSpacing="0px" VerticalPadding="0px" />
						<ParentNodeStyle Font-Bold="False" />
						<SelectedNodeStyle Font-Underline="True" ForeColor="#5555DD" 
							HorizontalPadding="0px" VerticalPadding="0px" />
						<LevelStyles>
							<asp:TreeNodeStyle NodeSpacing="10" />
							<asp:TreeNodeStyle Font-Bold="true" />
							<asp:TreeNodeStyle Font-Italic="true" />
						</LevelStyles>
					</asp:TreeView>
				</td>
			</tr>
		</table>
	</p>
</asp:Content>
