//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingClient.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2008/01", ConfigurationName="localhost.IMessageManagerService")]
    public interface IMessageManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2008/01/IMessageManagerService/SendMessage", ReplyAction="http://www.thatindigogirl.com/samples/2008/01/IMessageManagerService/SendMessageR" +
            "esponse")]
        string SendMessage(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2008/01/IMessageManagerService/SendOneWayMe" +
            "ssage", ReplyAction="http://www.thatindigogirl.com/samples/2008/01/IMessageManagerService/SendOneWayMe" +
            "ssageResponse")]
        void SendOneWayMessage(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMessageManagerServiceChannel : MessagingClient.localhost.IMessageManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MessageManagerServiceClient : System.ServiceModel.ClientBase<MessagingClient.localhost.IMessageManagerService>, MessagingClient.localhost.IMessageManagerService {
        
        public MessageManagerServiceClient() {
        }
        
        public MessageManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendMessage(string msg) {
            return base.Channel.SendMessage(msg);
        }
        
        public void SendOneWayMessage(string msg) {
            base.Channel.SendOneWayMessage(msg);
        }
    }
}
