//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CounterpartyAddress
    {
        public int CounterpartyId { get; set; }
        public int AddressID { get; set; }
        public int AddressTypeID { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual Address Address { get; set; }
        public virtual AddressType AddressType { get; set; }
    }
}
