//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.Data.Entities
{
    using System;
    
    public partial class InsertContactResult
    {
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid rowguid { get; set; }
        public int ContactID { get; set; }
    }
}
