//2008 IDesign Inc. 
//Questions? Comments? go to 
//http://www.idesign.net

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50215.44
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance","CA1811:AvoidUncalledPrivateCode",Scope="member",Target="Client.Properties.Settings.get_Default():Client.Properties.Settings")]

namespace Client.Properties
{


   [global::System.Runtime.CompilerServices.CompilerGenerated]
   internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
   {

      private static Settings defaultInstance = new Settings();

      public static Settings Default
      {
         get
         {
            return defaultInstance;
         }
      }
   }
}
