<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Territories.aspx.cs" Inherits="Northwind.UI.Linq.TerritoriesPage" Title="Territories" MasterPageFile="~/Northwind/Master/Northwind.master"%>

<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="NorthwindContentPlaceHolder" >
	<h2>Territories</h2>

		<p>
			This page demonstrates usage of <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.gridview.aspx" target="_blank">GridView</a>, 
			<a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.formview.aspx" target="_blank">FormView</a> and
			<a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.dropdownlist.aspx" target="_blank">DropDownList</a> with the 
			<a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.linqdatasource.aspx" target="_blank" >LinqDataSource</a>.
			DropDownList is used to implement master-details view. FormView is used for new record insertion.
		</p>
		<p>
			SqlDataSource uses parameter replacement technique to work with stored procedures instead of direct SQL statements.
		</p>
    <div>
		<asp:Panel ID="pnlData" runat="server">
			<%-- Note that WhereParameters are sufficient for SELECT and UPDATE, but not for INSERT and DELETE --%>
    		<asp:LinqDataSource ID="srcTerritories" runat="server" 
				ContextTypeName="Northwind.Data.Linq.NorthwindDataContext" TableName="Territories"
				Where="RegionID == @RegionID"
				EnableDelete="true" EnableInsert="true" EnableUpdate="true"
				OnContextCreating="srcTerritories_ContextCreating"
				OnDeleted="dataSource_SqlCommandDone"
				OnInserted="dataSource_SqlCommandDone" 
				OnSelected="dataSource_SqlCommandDone"
				OnUpdated="dataSource_SqlCommandDone" 
				OnSelecting="srcTerritories_Selecting" >
				<WhereParameters>
					<asp:ControlParameter ControlID="cmbRegions" Name="RegionID" 
						PropertyName="SelectedValue" Type="Int32" DefaultValue="1" />
				</WhereParameters>
				<InsertParameters>
					<asp:ControlParameter ControlID="cmbRegions" Name="RegionID" 
						PropertyName="SelectedValue" />
				</InsertParameters>
				<DeleteParameters>
					<asp:ControlParameter ControlID="cmbRegions" Name="RegionID" 
						PropertyName="SelectedValue" />
				</DeleteParameters>
				<%-- 
				<SelectParameters>
					<asp:ControlParameter ControlID="cmbRegions" Name="RegionID" 
						PropertyName="SelectedValue" />
				</SelectParameters>
				<UpdateParameters>
					<asp:ControlParameter ControlID="cmbRegions" Name="RegionID" 
						PropertyName="SelectedValue" />
				</UpdateParameters>
				--%>
			</asp:LinqDataSource>

			Select a region: 
			<asp:DropDownList ID="cmbRegions" runat="server" 
				DataTextField="RegionDescription" DataValueField="RegionID" AutoPostBack="True"
				OnSelectedIndexChanged="cmbRegions_SelectedIndexChanged">
			</asp:DropDownList>
			
			<asp:Panel runat="server" ID="pnlTerritories" Visible="false">
				<div>Region's territories:</div>
				
				<asp:GridView ID="grdTerritories" runat="server" AutoGenerateColumns="False" 
					DataKeyNames="TerritoryID" DataSourceID="srcTerritories" 
					AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateDeleteButton="True"
					AllowPaging="true"
					EnableSortingAndPagingCallbacks="true" PageSize="5">
					<PagerSettings Mode="NumericFirstLast" FirstPageText="|&lt;" LastPageText="&gt;|" PageButtonCount="3" />
					<Columns>
						<asp:BoundField DataField="TerritoryID" HeaderText="ID" 
							ReadOnly="True" SortExpression="TerritoryID" />
						<asp:BoundField DataField="TerritoryDescription" 
							HeaderText="Description" SortExpression="TerritoryDescription" />
					</Columns>
				</asp:GridView>
				<br />
				Define a new territory:
				<asp:FormView ID="frmTerritory" runat="server" 
					DataSourceID="srcTerritories" DefaultMode="Insert" Width="400px">
					<InsertItemTemplate>
						<table class="max_width">
							<tr>
								<td align="right" class="field_caption" width="25%">Description:</td>
								<td>
									<asp:TextBox ID="txtDescription" runat="server" MaxLength="50" 
										Text='<%# Bind("TerritoryDescription") %>' Width="100%"></asp:TextBox>
								</td>
							</tr>
							<tr>
								<td align="right" class="field_caption">ID:</td>
								<td>
									<asp:TextBox ID="txtID" runat="server" MaxLength="20" 
										Text='<%# Bind("TerritoryID") %>' Width="100%"></asp:TextBox>
								</td>
							</tr>
							<tr bgcolor="#CCCCFF">
								<td>
									<asp:Button ID="btnInsertTerritory" runat="server" CommandName="Insert" 
										Text="OK" Width="80px" />
								</td>
								<td align="right">
									<asp:Button ID="btnCancelTerritory" runat="server" CommandArgument="Cancel" 
										Text="Cancel" Width="80px" />
								</td>
							</tr>
						</table>
					</InsertItemTemplate>
				</asp:FormView>
			</asp:Panel>
		</asp:Panel>
		
		<asp:Label runat="server" ID="lblError" 
			Text="An error ocurred during accessing the database. Please try again later." 
			ForeColor="Red"
			Visible="false" />    
    </div>
</asp:Content>