<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Customers.aspx.cs" Inherits="Northwind.UI.Entities.CustomersPage" Title="Customers" MasterPageFile="~/Northwind/Master/Northwind.master"%>
<%@ Register Assembly="ControlExtensions" Namespace="ControlExtensions" TagPrefix="ce" %>
<%@ Import Namespace="Northwind" %>


<asp:Content ID="Content1" runat="server" ContentPlaceHolderID="NorthwindContentPlaceHolder" >
	<h2>Customers</h2>
	<p>This page demonstrates usage of <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.gridview.aspx" target="_blank">GridView</a>
	 with <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.entitydatasource.aspx" target="_blank">EntityDataSource</a> and
	 <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.queryextender.aspx" target="_blank">QueryExtender</a>.
	 <a href="http://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.detailsview.aspx" target="_blank">DetailsView</a>
	 is used to enter new data.
	</p>
    <div>
		<asp:Panel ID="pnlData" runat="server">

			<div style="margin-bottom: 10px">
				<span>Customer country:</span>
				<asp:DropDownList ID="cmbCountries" runat="server" 
					AutoPostBack="True" onselectedindexchanged="cmbCountries_SelectedIndexChanged"
					 />
			</div>
		
			<asp:EntityDataSource ID="srcCustomers" runat="server" 
				ContextTypeName="Northwind.Data.Entities.NorthwindObjectContext"
				ConnectionString="name=NorthwindEntities" 
				DefaultContainerName="NorthwindObjectContext" 
				EnableFlattening="False"
				EnableDelete="True" 
				EnableInsert="True" EnableUpdate="True" EntitySetName="Customers" 
				ondeleted="srcCustomers_WriteCommandDone" 
				oninserted="srcCustomers_WriteCommandDone" 
				onselected="srcCustomers_ReadCommandDone" 
				onupdated="srcCustomers_WriteCommandDone" />
			
			<asp:QueryExtender ID="qexCustomers" runat="server" 
				TargetControlID="srcCustomers">
				<asp:CustomExpression OnQuerying="qexCustomers_OnQuerying" />
			</asp:QueryExtender>
			
			<asp:GridView ID="grdCustomers" runat="server" AutoGenerateColumns="False" 
				DataSourceID="srcCustomers" DataKeyNames="CustomerID" AutoGenerateDeleteButton="True" 
				AutoGenerateEditButton="True" AllowSorting="True"
				AllowPaging="True" PageSize="20"
				onselectedindexchanged="grdCustomers_SelectedIndexChanged" 
				onrowupdated="grdCustomers_RowUpdated">
				<PagerSettings Mode="NextPrevious" NextPageText="Forward &gt;" 
					PreviousPageText="&lt; Back" />
				<Columns>
					<asp:CommandField ButtonType="Link" ShowSelectButton="true" SelectText="&gt;" />
					<asp:BoundField DataField="CustomerID" HeaderText="ID" SortExpression="CustomerID" />
					<asp:BoundField DataField="CompanyName" HeaderText="Company" 
						SortExpression="CompanyName" />
					<asp:BoundField DataField="ContactTitle" HeaderText="Contact Title"
						SortExpression="ContactTitle" />
					<asp:BoundField DataField="ContactName" HeaderText="Contact Name"
						SortExpression="ContactName" />
					<asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
					<asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
					<asp:BoundField DataField="Region" HeaderText="Region" SortExpression="Region" />
					<asp:BoundField DataField="PostalCode" HeaderText="Postal Code"
						SortExpression="PostalCode" />
					<asp:BoundField DataField="Country" HeaderText="Country" SortExpression="Country" />
					<asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone" />
					<asp:BoundField DataField="Fax" HeaderText="Fax" SortExpression="Fax" />
				</Columns>
			</asp:GridView>
			
			<br />
			New Customer:
			<asp:DetailsView ID="dvwNewCustomer" runat="server" 
				AutoGenerateInsertButton="True" AutoGenerateRows="False"
				DataKeyNames="ID" DataSourceID="srcCustomers" DefaultMode="Insert" 
				Height="50px" Width="125px" oniteminserted="dvwNewCustomer_ItemInserted">
				<Fields>
					<asp:BoundField DataField="CustomerID" HeaderText="ID" />
					<asp:BoundField DataField="CompanyName" HeaderText="Company" />
					<asp:BoundField DataField="ContactTitle" HeaderText="Contact Title" />
					<asp:BoundField DataField="ContactName" HeaderText="Contact Name" />
					<asp:BoundField DataField="Address" HeaderText="Address" />
					<asp:BoundField DataField="City" HeaderText="City" />
					<asp:BoundField DataField="Region" HeaderText="Region" />
					<asp:BoundField DataField="PostalCode" HeaderText="Postal Code" />
					<asp:BoundField DataField="Country" HeaderText="Country" />
					<asp:BoundField DataField="Phone" HeaderText="Phone" />
					<asp:BoundField DataField="Fax" HeaderText="Fax" />
				</Fields>
			</asp:DetailsView>
			
		</asp:Panel>
		<asp:Label runat="server" ID="lblError" 
			Text="An error ocurred during accessing the database. Please try again later." 
			ForeColor="Red"
			Visible="false" />    
    </div>
</asp:Content>
