// <auto-generated />
namespace CasinoModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1-21011")]
    public sealed partial class AddedSomeNewPropertyToCasino : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedSomeNewPropertyToCasino));
        
        string IMigrationMetadata.Id
        {
            get { return "201310311821192_AddedSomeNewPropertyToCasino"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
