//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.ContentManagerServiceV2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkItem", Namespace="http://alexeypr.com/Versioning/2015/10/")]
    [System.SerializableAttribute()]
    public partial class LinkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private string UrlField;
        
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://alexeypr.com/Versioning/2015/11", ConfigurationName="ContentManagerServiceV2.ContentManagerContract")]
    public interface ContentManagerContract {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://alexeypr.com/Versioning/2015/10) of message GetLinkItemRequest does not match the default value (http://alexeypr.com/Versioning/2015/11)
        [System.ServiceModel.OperationContractAttribute(Action="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/GetLinkItem", ReplyAction="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/GetLinkItemResponse" +
            "")]
        WCFTestClient.ContentManagerServiceV2.GetLinkItemResponse GetLinkItem(WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/GetLinkItem", ReplyAction="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/GetLinkItemResponse" +
            "")]
        System.Threading.Tasks.Task<WCFTestClient.ContentManagerServiceV2.GetLinkItemResponse> GetLinkItemAsync(WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://alexeypr.com/Versioning/2015/10) of message UpdateLinkItemRequest does not match the default value (http://alexeypr.com/Versioning/2015/11)
        [System.ServiceModel.OperationContractAttribute(Action="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/UpdateLinkItem", ReplyAction="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/UpdateLinkItemRespo" +
            "nse")]
        WCFTestClient.ContentManagerServiceV2.UpdateLinkItemResponse UpdateLinkItem(WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/UpdateLinkItem", ReplyAction="http://alexeypr.com/Versioning/2015/10/ContentManagerContract/UpdateLinkItemRespo" +
            "nse")]
        System.Threading.Tasks.Task<WCFTestClient.ContentManagerServiceV2.UpdateLinkItemResponse> UpdateLinkItemAsync(WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alexeypr.com/Versioning/2015/11/ContentManagerContract/DeleteLinkItem", ReplyAction="http://alexeypr.com/Versioning/2015/11/ContentManagerContract/DeleteLinkItemRespo" +
            "nse")]
        void DeleteLinkItem(WCFTestClient.ContentManagerServiceV2.LinkItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://alexeypr.com/Versioning/2015/11/ContentManagerContract/DeleteLinkItem", ReplyAction="http://alexeypr.com/Versioning/2015/11/ContentManagerContract/DeleteLinkItemRespo" +
            "nse")]
        System.Threading.Tasks.Task DeleteLinkItemAsync(WCFTestClient.ContentManagerServiceV2.LinkItem item);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLinkItem", WrapperNamespace="http://alexeypr.com/Versioning/2015/10", IsWrapped=true)]
    public partial class GetLinkItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alexeypr.com/Versioning/2015/10", Order=0)]
        public int id;
        
        public GetLinkItemRequest() {
        }
        
        public GetLinkItemRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLinkItemResponse", WrapperNamespace="http://alexeypr.com/Versioning/2015/10", IsWrapped=true)]
    public partial class GetLinkItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alexeypr.com/Versioning/2015/10", Order=0)]
        public WCFTestClient.ContentManagerServiceV2.LinkItem GetLinkItemResult;
        
        public GetLinkItemResponse() {
        }
        
        public GetLinkItemResponse(WCFTestClient.ContentManagerServiceV2.LinkItem GetLinkItemResult) {
            this.GetLinkItemResult = GetLinkItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLinkItem", WrapperNamespace="http://alexeypr.com/Versioning/2015/10", IsWrapped=true)]
    public partial class UpdateLinkItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alexeypr.com/Versioning/2015/10", Order=0)]
        public WCFTestClient.ContentManagerServiceV2.LinkItem item;
        
        public UpdateLinkItemRequest() {
        }
        
        public UpdateLinkItemRequest(WCFTestClient.ContentManagerServiceV2.LinkItem item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateLinkItemResponse", WrapperNamespace="http://alexeypr.com/Versioning/2015/10", IsWrapped=true)]
    public partial class UpdateLinkItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://alexeypr.com/Versioning/2015/10", Order=0)]
        public WCFTestClient.ContentManagerServiceV2.LinkItem UpdateLinkItemResult;
        
        public UpdateLinkItemResponse() {
        }
        
        public UpdateLinkItemResponse(WCFTestClient.ContentManagerServiceV2.LinkItem UpdateLinkItemResult) {
            this.UpdateLinkItemResult = UpdateLinkItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContentManagerContractChannel : WCFTestClient.ContentManagerServiceV2.ContentManagerContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContentManagerContractClient : System.ServiceModel.ClientBase<WCFTestClient.ContentManagerServiceV2.ContentManagerContract>, WCFTestClient.ContentManagerServiceV2.ContentManagerContract {
        
        public ContentManagerContractClient() {
        }
        
        public ContentManagerContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContentManagerContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentManagerContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContentManagerContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.ContentManagerServiceV2.GetLinkItemResponse WCFTestClient.ContentManagerServiceV2.ContentManagerContract.GetLinkItem(WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest request) {
            return base.Channel.GetLinkItem(request);
        }
        
        public WCFTestClient.ContentManagerServiceV2.LinkItem GetLinkItem(int id) {
            WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest inValue = new WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest();
            inValue.id = id;
            WCFTestClient.ContentManagerServiceV2.GetLinkItemResponse retVal = ((WCFTestClient.ContentManagerServiceV2.ContentManagerContract)(this)).GetLinkItem(inValue);
            return retVal.GetLinkItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFTestClient.ContentManagerServiceV2.GetLinkItemResponse> WCFTestClient.ContentManagerServiceV2.ContentManagerContract.GetLinkItemAsync(WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest request) {
            return base.Channel.GetLinkItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFTestClient.ContentManagerServiceV2.GetLinkItemResponse> GetLinkItemAsync(int id) {
            WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest inValue = new WCFTestClient.ContentManagerServiceV2.GetLinkItemRequest();
            inValue.id = id;
            return ((WCFTestClient.ContentManagerServiceV2.ContentManagerContract)(this)).GetLinkItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.ContentManagerServiceV2.UpdateLinkItemResponse WCFTestClient.ContentManagerServiceV2.ContentManagerContract.UpdateLinkItem(WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest request) {
            return base.Channel.UpdateLinkItem(request);
        }
        
        public WCFTestClient.ContentManagerServiceV2.LinkItem UpdateLinkItem(WCFTestClient.ContentManagerServiceV2.LinkItem item) {
            WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest inValue = new WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest();
            inValue.item = item;
            WCFTestClient.ContentManagerServiceV2.UpdateLinkItemResponse retVal = ((WCFTestClient.ContentManagerServiceV2.ContentManagerContract)(this)).UpdateLinkItem(inValue);
            return retVal.UpdateLinkItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFTestClient.ContentManagerServiceV2.UpdateLinkItemResponse> WCFTestClient.ContentManagerServiceV2.ContentManagerContract.UpdateLinkItemAsync(WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest request) {
            return base.Channel.UpdateLinkItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFTestClient.ContentManagerServiceV2.UpdateLinkItemResponse> UpdateLinkItemAsync(WCFTestClient.ContentManagerServiceV2.LinkItem item) {
            WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest inValue = new WCFTestClient.ContentManagerServiceV2.UpdateLinkItemRequest();
            inValue.item = item;
            return ((WCFTestClient.ContentManagerServiceV2.ContentManagerContract)(this)).UpdateLinkItemAsync(inValue);
        }
        
        public void DeleteLinkItem(WCFTestClient.ContentManagerServiceV2.LinkItem item) {
            base.Channel.DeleteLinkItem(item);
        }
        
        public System.Threading.Tasks.Task DeleteLinkItemAsync(WCFTestClient.ContentManagerServiceV2.LinkItem item) {
            return base.Channel.DeleteLinkItemAsync(item);
        }
    }
}
