'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization

Namespace TaskWcfService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Task", [Namespace]:="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")>  _
    Partial Public Class Task
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private AssignedToField As String
        
        Private DescriptionField As String
        
        Private DueDateField As Date
        
        Private StatusField As TaskWcfService.TaskStatus
        
        Private TaskNumberField As Integer
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AssignedTo() As String
            Get
                Return Me.AssignedToField
            End Get
            Set
                Me.AssignedToField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Description() As String
            Get
                Return Me.DescriptionField
            End Get
            Set
                Me.DescriptionField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DueDate() As Date
            Get
                Return Me.DueDateField
            End Get
            Set
                Me.DueDateField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As TaskWcfService.TaskStatus
            Get
                Return Me.StatusField
            End Get
            Set
                Me.StatusField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TaskNumber() As Integer
            Get
                Return Me.TaskNumberField
            End Get
            Set
                Me.TaskNumberField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="TaskStatus", [Namespace]:="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")>  _
    Public Enum TaskStatus As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [New] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Assigned = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Overdue = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CompletedOnTime = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CompletedLate = 4
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FaultInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")>  _
    Partial Public Class FaultInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private ErrorMessageField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                Me.ErrorMessageField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="TaskWcfService.ITaskService")>  _
    Public Interface ITaskService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITaskService/AddTask", ReplyAction:="http://tempuri.org/ITaskService/AddTaskResponse")>  _
        Function AddTask(ByVal t As TaskWcfService.Task) As Integer
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/AddTask", ReplyAction:="http://tempuri.org/ITaskService/AddTaskResponse")>  _
        Function BeginAddTask(ByVal t As TaskWcfService.Task, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndAddTask(ByVal result As System.IAsyncResult) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITaskService/GetTask", ReplyAction:="http://tempuri.org/ITaskService/GetTaskResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TaskWcfService.FaultInfo), Action:="http://tempuri.org/ITaskService/GetTaskFaultInfoFault", Name:="FaultInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")>  _
        Function GetTask(ByVal taskNumber As Integer) As TaskWcfService.Task
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/GetTask", ReplyAction:="http://tempuri.org/ITaskService/GetTaskResponse")>  _
        Function BeginGetTask(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetTask(ByVal result As System.IAsyncResult) As TaskWcfService.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITaskService/AssignTask", ReplyAction:="http://tempuri.org/ITaskService/AssignTaskResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TaskWcfService.FaultInfo), Action:="http://tempuri.org/ITaskService/AssignTaskFaultInfoFault", Name:="FaultInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")>  _
        Sub AssignTask(ByVal taskNumber As Integer, ByVal owner As String)
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/AssignTask", ReplyAction:="http://tempuri.org/ITaskService/AssignTaskResponse")>  _
        Function BeginAssignTask(ByVal taskNumber As Integer, ByVal owner As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndAssignTask(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITaskService/GetTasksByOwner", ReplyAction:="http://tempuri.org/ITaskService/GetTasksByOwnerResponse")>  _
        Function GetTasksByOwner(ByVal owner As String) As TaskWcfService.Task()
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/GetTasksByOwner", ReplyAction:="http://tempuri.org/ITaskService/GetTasksByOwnerResponse")>  _
        Function BeginGetTasksByOwner(ByVal owner As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetTasksByOwner(ByVal result As System.IAsyncResult) As TaskWcfService.Task()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITaskService/IsTaskCompleted", ReplyAction:="http://tempuri.org/ITaskService/IsTaskCompletedResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(TaskWcfService.FaultInfo), Action:="http://tempuri.org/ITaskService/IsTaskCompletedFaultInfoFault", Name:="FaultInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/TaskService.BusinessEntities")>  _
        Function IsTaskCompleted(ByVal taskNumber As Integer) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/IsTaskCompleted", ReplyAction:="http://tempuri.org/ITaskService/IsTaskCompletedResponse")>  _
        Function BeginIsTaskCompleted(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndIsTaskCompleted(ByVal result As System.IAsyncResult) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/ITaskService/MarkTaskCompleted")>  _
        Sub MarkTaskCompleted(ByVal taskNumber As Integer)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/MarkTaskCompleted")>  _
        Function BeginMarkTaskCompleted(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndMarkTaskCompleted(ByVal result As System.IAsyncResult)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/ITaskService/DeleteTask")>  _
        Sub DeleteTask(ByVal taskNumber As Integer)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/ITaskService/DeleteTask")>  _
        Function BeginDeleteTask(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndDeleteTask(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITaskServiceChannel
        Inherits TaskWcfService.ITaskService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TaskServiceClient
        Inherits System.ServiceModel.ClientBase(Of TaskWcfService.ITaskService)
        Implements TaskWcfService.ITaskService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AddTask(ByVal t As TaskWcfService.Task) As Integer Implements TaskWcfService.ITaskService.AddTask
            Return MyBase.Channel.AddTask(t)
        End Function
        
        Public Function BeginAddTask(ByVal t As TaskWcfService.Task, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginAddTask
            Return MyBase.Channel.BeginAddTask(t, callback, asyncState)
        End Function
        
        Public Function EndAddTask(ByVal result As System.IAsyncResult) As Integer Implements TaskWcfService.ITaskService.EndAddTask
            Return MyBase.Channel.EndAddTask(result)
        End Function
        
        Public Function GetTask(ByVal taskNumber As Integer) As TaskWcfService.Task Implements TaskWcfService.ITaskService.GetTask
            Return MyBase.Channel.GetTask(taskNumber)
        End Function
        
        Public Function BeginGetTask(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginGetTask
            Return MyBase.Channel.BeginGetTask(taskNumber, callback, asyncState)
        End Function
        
        Public Function EndGetTask(ByVal result As System.IAsyncResult) As TaskWcfService.Task Implements TaskWcfService.ITaskService.EndGetTask
            Return MyBase.Channel.EndGetTask(result)
        End Function
        
        Public Sub AssignTask(ByVal taskNumber As Integer, ByVal owner As String) Implements TaskWcfService.ITaskService.AssignTask
            MyBase.Channel.AssignTask(taskNumber, owner)
        End Sub
        
        Public Function BeginAssignTask(ByVal taskNumber As Integer, ByVal owner As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginAssignTask
            Return MyBase.Channel.BeginAssignTask(taskNumber, owner, callback, asyncState)
        End Function
        
        Public Sub EndAssignTask(ByVal result As System.IAsyncResult) Implements TaskWcfService.ITaskService.EndAssignTask
            MyBase.Channel.EndAssignTask(result)
        End Sub
        
        Public Function GetTasksByOwner(ByVal owner As String) As TaskWcfService.Task() Implements TaskWcfService.ITaskService.GetTasksByOwner
            Return MyBase.Channel.GetTasksByOwner(owner)
        End Function
        
        Public Function BeginGetTasksByOwner(ByVal owner As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginGetTasksByOwner
            Return MyBase.Channel.BeginGetTasksByOwner(owner, callback, asyncState)
        End Function
        
        Public Function EndGetTasksByOwner(ByVal result As System.IAsyncResult) As TaskWcfService.Task() Implements TaskWcfService.ITaskService.EndGetTasksByOwner
            Return MyBase.Channel.EndGetTasksByOwner(result)
        End Function
        
        Public Function IsTaskCompleted(ByVal taskNumber As Integer) As Boolean Implements TaskWcfService.ITaskService.IsTaskCompleted
            Return MyBase.Channel.IsTaskCompleted(taskNumber)
        End Function
        
        Public Function BeginIsTaskCompleted(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginIsTaskCompleted
            Return MyBase.Channel.BeginIsTaskCompleted(taskNumber, callback, asyncState)
        End Function
        
        Public Function EndIsTaskCompleted(ByVal result As System.IAsyncResult) As Boolean Implements TaskWcfService.ITaskService.EndIsTaskCompleted
            Return MyBase.Channel.EndIsTaskCompleted(result)
        End Function
        
        Public Sub MarkTaskCompleted(ByVal taskNumber As Integer) Implements TaskWcfService.ITaskService.MarkTaskCompleted
            MyBase.Channel.MarkTaskCompleted(taskNumber)
        End Sub
        
        Public Function BeginMarkTaskCompleted(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginMarkTaskCompleted
            Return MyBase.Channel.BeginMarkTaskCompleted(taskNumber, callback, asyncState)
        End Function
        
        Public Sub EndMarkTaskCompleted(ByVal result As System.IAsyncResult) Implements TaskWcfService.ITaskService.EndMarkTaskCompleted
            MyBase.Channel.EndMarkTaskCompleted(result)
        End Sub
        
        Public Sub DeleteTask(ByVal taskNumber As Integer) Implements TaskWcfService.ITaskService.DeleteTask
            MyBase.Channel.DeleteTask(taskNumber)
        End Sub
        
        Public Function BeginDeleteTask(ByVal taskNumber As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements TaskWcfService.ITaskService.BeginDeleteTask
            Return MyBase.Channel.BeginDeleteTask(taskNumber, callback, asyncState)
        End Function
        
        Public Sub EndDeleteTask(ByVal result As System.IAsyncResult) Implements TaskWcfService.ITaskService.EndDeleteTask
            MyBase.Channel.EndDeleteTask(result)
        End Sub
    End Class
End Namespace
